### ISSUE TITLE
Documentation incorrect for options without arguments

### ISSUE THREAD

**Issue by jberger** [kingpong/perl-PDF-WebKit#2]
I believe that the documentation is in error [saying](https://github.com/kingpong/perl-PDF-WebKit/blob/fd85d31f3fa33e5e20ba72297492d9d0d7f458dd/lib/PDF/WebKit.pm#L294-L295):

> For options with no associated value, pass `C<undef>` as
the value.

It seems that to pass an option with no associated value, [passing `yes` or `YES` is required](https://github.com/kingpong/perl-PDF-WebKit/blob/fd85d31f3fa33e5e20ba72297492d9d0d7f458dd/lib/PDF/WebKit.pm#L192). While I don't especially like that mechanism (I think undef would likely be fine, or else a case insensitive regexp match or somehting) the documentation should at least agree with the behavior.

**Comment by kingpong** [comment]
Thanks for the report. Unfortunately undef will not work since that is the mechanism for overriding/removing the default arguments that PDF::WebKit applies. I've updated the documentation and made it a true case-insensitive comparison so you can pass 'yeS' if you want.  Fixed in version 1.0 which should be on CPAN soon.

**Comment by jberger** [comment]
Thanks!
